language: go

go:
  - 1.x
  - 1.7.x
  - 1.8.x


after_script: # here's a build step block
- npm update -g n
- npm update npm -g
- node -v
- nohup go run main.go > /dev/null 2>&1 &
- npm install -g newman
- newman run ./PostManTests/web.postman_collection.json