language: go

go:
  - 1.x
  - 1.7.x
  - 1.8.x


after_script: # here's a build step block
- echo "We can put normal shell commands here"
- echo "more shell commands here"
- nohup go run main.go > /dev/null 2>&1 &