CREATE TABLE User(
  `ID` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  `Email` CHAR(80) NOT NULL,
  `FirstName` CHAR(55) NOT NULL,
  `LastName` CHAR(55) NOT NULL,
  `Password` CHAR(256) NOT NULL
);

CREATE TABLE Receipt(
  `ID` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  `ImagePath` CHAR(100) NOT NULL,
  `Data` TEXT NOT NULL
);

CREATE TABLE Project(
  `ID` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  `Name` CHAR(10) NOT NULL
);

CREATE TABLE Declaration(
  `ID` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  `Title` CHAR(10) NOT NULL,
  `TotalPrice` DECIMAL(10) NOT NULL,
  `VATPrice` DECIMAL(10) NOT NULL,
  `Date` DATETIME NOT NULL,
  `Description` VARCHAR(255) NOT NULL,
  `ProjectID` INTEGER NOT NULL,
  `StoreName` CHAR(100) NOT NULL,
  `ReceiptID` INTEGER NOT NULL,
  `UserID` INTEGER NOT NULL,
  FOREIGN KEY (`ProjectID`) REFERENCES Project(`ID`),
  FOREIGN KEY (`ReceiptID`) REFERENCES Receipt(`ID`),
  FOREIGN KEY (`UserID`) REFERENCES User(`ID`)
);

CREATE TABLE DeclarationStatus(
  `ID` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  `Status` VARCHAR(20) NOT NULL,
  `DateModifed` DATETIME NOT NULL,
  `DeclarationID` INTEGER NOT NULL,
  `ModifiedByUserID` INTEGER NOT NULL,
  FOREIGN KEY (`DeclarationID`) REFERENCES Declaration(`ID`),
  FOREIGN KEY (`ModifiedByUserID`) REFERENCES User(`ID`)
);

CREATE TABLE UserProject(
  `ProjectID` INTEGER NOT NULL,
  `UserID` INTEGER NOT NULL,
  FOREIGN KEY (`ProjectID`) REFERENCES Project(`ID`),
  FOREIGN KEY (`UserID`) REFERENCES User(`ID`)
);